# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSfe_twsMTbjdlMkOVzSexN-hbX9NSpC
"""



from flask import Flask, jsonify, render_template
import random

app = Flask(__name__)

# List of compliments
compliments = ["You are awesome!", "Great job!", "Well done!", "Fantastic!", "Keep it up!"]

# Route for homepage
@app.route("/")
def index():
    return render_template("index.html")  # your HTML page will go in templates/index.html

# Route to get a random compliment
@app.route("/compliment")
def get_compliment():
    return jsonify({"compliment": random.choice(compliments)})

if __name__ == "__main__":
    app.run(debug=True)